version: "3"
services:
  mailhog:
    build: 
      context: './mailhog'
    ports:
      - "1025:1025"
      - "${MAILHOG_PORT}:8025"
  apache_with_php:
    build:
      context: './apache'
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/www/html"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
volumes: {}
