name: Mailhog 

on:
  schedule:
  - cron:  '30 19 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Mailhog-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:40687/)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Curl Test
      run: curl -i http://localhost:40687/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>" 
        mention_users: "D056LFW47NF,"
        mention_users_when: "SUCCESS"
        mention_groups: "C06H0SB11JL"
        mention_groups_when: "SUCCESS"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>"
        mention_users: "D056LFW47NF"
        mention_users_when: "failure,warnings"
        mention_groups: "C06G95T1YH3"
        mention_groups_when: "failure,warnings"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  Mailhog-ARM64:
    runs-on: ubuntu-22.04
    name: Mailhog-ARM64
    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)

    - name: Get the output
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:40687/)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Curl Test
      run: curl -i http://localhost:40687/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>" 
        mention_users: "D056LFW47NF,"
        mention_users_when: "SUCCESS"
        mention_groups: "C06H0SB11JL"
        mention_groups_when: "SUCCESS"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>"
        mention_users: "D056LFW47NF"
        mention_users_when: "failure,warnings"
        mention_groups: "C06G95T1YH3"
        mention_groups_when: "failure,warnings"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  
