name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Mailhog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image mailhog
        run: docker-compose -f "docker-compose.yml" up -d --build