name: Mailhog 

on:
  schedule:
  - cron:  '30 1 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Mailhog-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:40687/)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Curl Test
      run: curl -i http://localhost:40687/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
  Mailhog-ARM64:
    runs-on: ubuntu_latest
    steps:
    - uses: uraimo/run-on-arch-action@v2.3.0
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:40687/)" != "200" ]]; 
        do 
          sleep 10s
        done
    - name: Curl Test
      run: curl -i http://localhost:40687/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a