name: Laravel 

on:
  schedule:
  - cron:  '30 1 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Mailhog-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run: curl -i http://localhost:40687/
  Mailhog-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image mailhog
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Image Test 
      run: curl -i http://localhost:40687/